### ISSUE TITLE
Support for msync

### ISSUE THREAD

**Issue by posix4e** [danburkert/mmap#3]
There's no reason to flush all outstanding changes in all cases. It might be nice if we supported msync

**Comment by posix4e** [comment]
So looking at your code, it would be nice if flush could take a start and end or start and length argument that you pass to async. BTW MS_ASYNC does nothing nowadays

    pub fn flush(&mut self) -> io::Result<()> {
        let result = unsafe { libc::msync(self.ptr, self.len as libc::size_t, libc::MS_SYNC) };
        if result == 0 {
            Ok(())
        } else {
            Err(io::Error::last_os_error())
        }
    }

    pub fn flush_async(&mut self) -> io::Result<()> {
        let result = unsafe { libc::msync(self.ptr, self.len as libc::size_t, libc::MS_ASYNC) };
        if result == 0 {
            Ok(())
        } else {
            Err(io::Error::last_os_error())
        }

    }

**Comment by posix4e** [comment]
According to POSIX, either MS_SYNC or MS_ASYNC  must  be  specified  in
       flags,  and  indeed  failure  to  include one of these flags will cause
       msync() to fail on some systems.  However,  Linux  permits  a  call  to
       msync()  that specifies neither of these flags, with semantics that are
       (currently) equivalent to specifying MS_ASYNC.   (Since  Linux  2.6.19,
       MS_ASYNC  is  in  fact  a no-op, since the kernel properly tracks dirty
       pages and flushes them to storage as necessary.)   Notwithstanding  the
       Linux  behavior, portable, future-proof applications should ensure that
       they specify either MS_SYNC or MS_ASYNC in flags.

**Comment by danburkert** [comment]
One thing I intended to add to the API was a way to get a slice of the mmap back as another owned mmap.  Kind of like the following:

```rust
let map: Mmap = Mmap::open("/temp/foo", Protection::Read).unwrap();
let sub_view: Mmap = map[10..110];

// at this point sub_view is a full blow memory map with no lifetime restrictions.
// It can be flushed independently of the 'spawning' mmap.

sub_view.flush();

*map[42] = 3;  // The original map is not borrowed
```

But now that I think about it I can't remember if I didn't do this because I forgot, or because it's not possible to do efficiently.  If not, a more flexible flush would be good.

**Comment by posix4e** [comment]
Wow , you are right that slice would be dope. Otherwise, we can provide a length/position

**Comment by danburkert** [comment]
fixed with the recent `MmapView`/`flush_range` changes.
