### ISSUE TITLE
How to slice up mmap to share chunks of the same mmap?

### ISSUE THREAD

**Issue by xrl** [danburkert/mmap#7]
I am working on a mmap-powered database driver, whose main struct looks like this:

```
pub struct WhisperFile<'a> {
	pub path: PathBuf,
	pub mmap: Mmap,
	pub header: Header,
	pub archives: Vec< Archive<'a> >,
}
```

I want the `Archive`s to get their slice of the `mmap` property. But I can't figure out the rust lifetime gymnastics. Think it can be done? Seems safe if they're all tied to lifetime `'a`. Any tips?

**Comment by xrl** [comment]
Upon further thought, the `Archive` have non-overlapping slices. Could functionality similar to split_at_mut work?

**Comment by xrl** [comment]
Someone said "just use Rc" so I cranked out a pretty slick solution. Please check it out here: https://users.rust-lang.org/t/designing-api-based-on-slices-of-mmap/2323 . Feedback is greatly appreciated. Perhaps a "MmapView" would be handy in this library?

**Comment by xrl** [comment]
And now I'm reading about Rust 1.2 and Dynamically Sized Types. Could they be useful for this feature? http://smallcultfollowing.com/babysteps/blog/2014/01/05/dst-take-5/

**Comment by danburkert** [comment]
@xrl I think your solution is pretty good, my only concern is about the unsafety issues outlined in #4, but if you are careful to never mutate the file from another thread or process everything should be OK.  DST is alive and well in Rust today, but the syntax looks very different from that blog post (a year and a half is an eternity in Rust years).  As it stands, DST won't really help you, the `Deref` trait is the right path, though.

Long-term I want to explore how Kimundi/owning-ref-rs might fit in with mmap'd memory.  Could be an interesting solution to this problem.

**Comment by danburkert** [comment]
I should clarify: it's not good enough to just check whether another thread or process mutates the file, you need to check wether *anyone* else mutates the file, even the current thread through another handle to the file.

**Comment by danburkert** [comment]
@xrl I'm closing since the `MmapView` changes just landed.  Feel free to reopen if you feel there are more API changes that should be made.  Thanks!
